version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=moj_korisnik
      - POSTGRES_PASSWORD=moja_lozinka
    ports:
      - "5433:5432"
    volumes:
      - moj_db:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=moj_korisnik
      - SPRING_DATASOURCE_PASSWORD=moja_lozinka

volumes:
  moj_db:
    driver: local